from worlds.mhw.game_id import mhw_weapon_id

insect_glaives_weapon_category = 10


def get_id(base_id):
    return mhw_weapon_id + insect_glaives_weapon_category * 1000 + base_id

# Giving an insect glaive, equipping it and then hovering over a kinsect crashes the game
# https://mhw.poedb.tw/eng/wp_weapon
insect_glaives_by_rarity = {
    0: {
        #       get_id(10): "Iron Blade I",
        get_id(11): "Iron Blade II",
        get_id(48): "Bone Rod I",
        get_id(49): "Bone Rod II",
    },
    1: {
        get_id(12): "Iron Blade III",
        get_id(25): "Kulu Blade I",
        get_id(40): "Blooming Glaive I",
        get_id(50): "Bone Rod III",
        get_id(61): "Aqua Rod I",
        get_id(72): "Pulsar Rod I",
    },
    2: {
        get_id(13): "Steel Blade I",
        get_id(26): "Kulu Blade II",
        get_id(31): "Luminous Blade I",
        get_id(41): "Blooming Glaive II",
        get_id(51): "Hard Bone Rod I",
        get_id(51): "Flammenkaefer",
        get_id(73): "Pulsar Rod II",
        get_id(82): "Dragonbone Glaive I",
    },
    3: {
        get_id(14): "Steel Blade II",
        get_id(20): "Flame Glaive I",
        get_id(27): "Kulu Blade III",
        get_id(32): "Luminous Blade II",
        get_id(36): "Frost Blade I",
        get_id(42): "Blooming Glaive III",
        get_id(52): "Hard Bone Rod II",
        get_id(63): "Aqua Rod III",
        get_id(67): "Diablos Rod I",
        get_id(74): "Pulsar Rod III",
        get_id(78): "Garon Rod I",
        get_id(83): "Dragonbone Glaive II",
        get_id(85): "Indigo Flash",
    },
    4: {
        get_id(15): "Steel Blade III",
        get_id(21): "Flame Glaive II",
        get_id(28): "Ya-Ku Wrath I",
        get_id(33): "Destroyer Bo I",
        get_id(37): "Frost Blade II",
        get_id(43): "Datura Blade I",
        get_id(53): "Hard Bone Rod III",
        get_id(59): "Flammenkaefer+",
        get_id(64): "Water Glaive I",
        get_id(75): "Kadachi Pillar I",
        get_id(79): "Garon Rod II",
        get_id(88): "Blacksteel Glaive I",
    },
    5: {
        get_id(16): "Chrome Blade I",
        get_id(17): "Chrome Blade II",
        get_id(22): "Rathmaul",
        get_id(29): "Ya-Ku Wrath II",
        get_id(30): "Ya-Ku Wrath III",
        get_id(34): "Destroyer Bo II",
        get_id(35): "Destroyer Bo III",
        get_id(38): "Freeze Gale I",
        get_id(39): "Freeze Gale II",
        get_id(44): "Datura Blade II",
        get_id(45): "Datura Blade III",
        get_id(46): "Gama Cane I",
        get_id(54): "Aerial Rod I",
        get_id(55): "Aerial Rod II",
        get_id(65): "Water Glaive II",
        get_id(66): "Water Glaive III",
        get_id(69): "Tyrannis Glaive I",
        get_id(76): "Kadachi Pillar II",
        get_id(77): "Kadachi Pillar III",
        get_id(80): "Temptation's Trident",
        get_id(84): "Dragonbone Glaive III",
        get_id(89): "Blacksteel Glaive II",
        get_id(100): "Bad Wing",
        # https://monsterhunterworld.wiki.fextralife.com/Kulve+Taroth
        get_id(105): "Gold Ice Naginata",
        get_id(106): "Gold Paralysis Naginata",
        get_id(107): "Thief Gold Naginata",
        get_id(108): "Spew Gold Naginata",
        get_id(109): "Spark Gold Naginata",
        get_id(110): "Flash Gold Naginata",
        get_id(111): "Claw Gold Naginata",
        get_id(112): "Decay Gold Naginata",
        get_id(113): "King Gold Naginata",
        get_id(114): "Horn Gold Naginata",
        get_id(115): "Crusher Gold Naginata",
    },
    6: {
        get_id(18): "Nergal Reaper",
        get_id(23): "Firedance Rathmaul",
        get_id(47): "Gama Cane II",
        get_id(56): "Hazak Entoma I",
        get_id(57): "Hazak Entoma II",
        get_id(60): "Gnashing Flammenkaefer",
        get_id(70): "Tyrannis Glaive II",
        get_id(86): "Azure Bolt",
        get_id(90): "Daora's Entom",
        get_id(101): "Grunge Storm",
        get_id(102): "Gae Bolg",
        get_id(128): "Empress Cane",
        # https://monsterhunterworld.wiki.fextralife.com/Kulve+Taroth
        get_id(116): "Taroth Glaive Thief",
        get_id(117): "Taroth Glaive Spew",
        get_id(118): "Taroth Glaive Spark",
        get_id(119): "Taroth Glaive Flash",
        get_id(120): "Taroth Glaive Claw",
        get_id(121): "Taroth Glaive Decay",
        get_id(122): "Taroth Glaive King",
        get_id(123): "Taroth Glaive Horn",
        get_id(124): "Taroth Glaive Crusher",
    },
    7: {
        get_id(19): "Catastrophe's Light",
        get_id(81): "Vice",
        get_id(87): "Verdant Levin",
        get_id(91): "Daora's Tethidine",
        get_id(92): "Xeno Shmaena",
        get_id(103): "True Gae Bolg",
        get_id(129): "Empress Cane Blaze",
        get_id(130): "Empress Cane Ruin",
        get_id(131): "Empress Cane Styx",
        # https://monsterhunterworld.wiki.fextralife.com/Kulve+Taroth
        get_id(125): "Taroth Glaive Water",
        get_id(126): "Taroth Glaive Ice",
        get_id(127): "Taroth Glaive Paralysis",
        get_id(132): "Taroth Glaive Sleep",
        get_id(133): "Taroth Glaive Spark",
        get_id(134): "Taroth Glaive Decay",
        get_id(135): "Taroth Glaive King",
        get_id(136): "Taroth Glaive Crusher",
        get_id(137): "Taroth Glaive Water",
        get_id(138): "Taroth Glaive Ice",
        get_id(139): "Taroth Glaive Paralysis",
    },
}
