from ..game_id import mhw_armor_id

def get_id(base_id):
    return mhw_armor_id + base_id * 10

# https://mhw.poedb.tw/eng/pl_equip
armor_sets_by_rarity = {
    0: {
#        get_id(2): "Leather",
        get_id(1): "Hunter",
        get_id(4): "Jagras",
        get_id(5): "Bone",
        # get_id(8): "Gajau", # Legs only
        get_id(9): "Vespoid",
        get_id(10): "Kulu",
#        get_id(15): "Chainmail",
    },
    1: {
        get_id(6): "Alloy",
        get_id(11): "Pukei",
        get_id(12): "Jyura",
        get_id(13): "Barroth",
        get_id(14): "Kadachi",
    },
    2: {
        get_id(3): "Anja",
        get_id(18): "Hornetaur",
        get_id(21): "Rathian",
        get_id(22): "Girros",
        get_id(23): "Tzitzi",
        get_id(24): "Lumu",
        get_id(25): "High Metal",
        get_id(28): "Baan",
        get_id(193): "Blossom",
        get_id(194): "Diver",
        get_id(195): "Harvest",
    },
    3: {
        get_id(26): "Death Stench",
        get_id(27): "Legiana",
        get_id(29): "Odogaron",
        get_id(31): "Ingot",
        get_id(33): "Rathalos",
        get_id(34): "Diablos",
        get_id(35): "Kirin",
        get_id(36): "Brigade",
        get_id(196): "Orion",
        get_id(197): "Gala Suit",
    },
    4: {
        get_id(39): "Leather Alpha",
        get_id(40): "Leather Beta",
        get_id(41): "Hunter Alpha",
        get_id(42): "Hunter Beta",
        get_id(43): "Bone Alpha",
        get_id(44): "Bone Beta",
        get_id(45): "Alloy Alpha",
        get_id(46): "Alloy Beta",
        get_id(51): "Vespoid Alpha",
        get_id(52): "Vespoid Beta",
        get_id(57): "Hornetaur Alpha",
        get_id(58): "Hornetaur Beta",
        get_id(61): "Jagras Alpha",
        get_id(62): "Jagras Beta",
        get_id(63): "Kulu Alpha",
        get_id(64): "Kulu Beta",
        get_id(65): "Pukei Alpha",
        get_id(66): "Pukei Beta",
        get_id(67): "Jyura Alpha",
        get_id(68): "Jyura Beta",
        get_id(69): "Barroth Alpha",
        get_id(70): "Barroth Beta",
        get_id(71): "Kadachi Alpha",
        get_id(72): "Kadachi Beta",
        get_id(73): "Rathian Alpha",
        get_id(74): "Rathian Beta",
        get_id(75): "Girros Alpha",
        get_id(76): "Girros Beta",
        get_id(77): "Tzitzi Alpha",
        get_id(78): "Tzitzi Beta",
        get_id(79): "Lumu Alpha",
        get_id(80): "Lumu Beta",
        get_id(83): "Dodogama Alpha",
        get_id(84): "Dodogama Beta",
        get_id(85): "Lavasioth Alpha",
        get_id(86): "Lavasioth Beta",
        get_id(93): "Anja Alpha",
        get_id(94): "Anja Beta",
        get_id(147): "Chainmail Alpha",
        get_id(148): "Chainmail Beta",
        get_id(207): "Blossom Alpha",
        get_id(208): "Diver Alpha",
    },
    5: {
        get_id(81): "Odogaron Alpha",
        get_id(82): "Odogaron Beta",
        get_id(87): "Rath Heart Alpha",
        get_id(88): "Rath Heart Beta",
        get_id(89): "High Metal Alpha",
        get_id(90): "High Metal Beta",
        get_id(91): "Ingot Alpha",
        get_id(92): "Ingot Beta",
        get_id(95): "Legiana Alpha",
        get_id(96): "Legiana Beta",
        get_id(97): "Baan Alpha",
        get_id(98): "Baan Beta",
        get_id(101): "Rathalos Alpha",
        get_id(102): "Rathalos Beta",
        get_id(103): "Diablos Alpha",
        get_id(102): "Diablos Beta",
        get_id(119): "Brigade Alpha",
        get_id(120): "Brigade Beta",
        get_id(137): "Zorah Alpha",
        get_id(138): "Zorah Beta",
        get_id(209): "Harvest Alpha",
        get_id(210): "Orion Alpha",
    },
    6: {
        get_id(109): "Uragaan Alpha",
        get_id(110): "Uragaan Beta",
        get_id(111): "Rath Soul Alpha",
        get_id(112): "Rath Soul Beta",
        get_id(113): "Diablos Nero Alpha",
        get_id(114): "Diablos Nero Beta",
        get_id(121): "Damascus Alpha",
        get_id(122): "Damascus Beta",
        get_id(123): "Dober Alpha",
        get_id(124): "Dober Beta",
        get_id(201): "Vangis Alpha",
        get_id(202): "Vangis Beta",
        get_id(211): "Gala Suit Alpha",
    },
    7: {
        get_id(99): "Vaal Hazak Alpha",
        get_id(100): "Vaal Hazak Beta",
        get_id(105): "Kirin Alpha",
        get_id(106): "Kirin Beta",
        get_id(107): "Nergigante Alpha",
        get_id(108): "Nergigante Beta",
        get_id(115): "Bazel Alpha",
        get_id(116): "Bazel Beta",
        get_id(125): "Xeno'jiiva Alpha",
        get_id(126): "Xeno'jiiva Beta",
        get_id(127): "Kaiser Alpha",
        get_id(128): "Kaiser Beta",
        get_id(129): "Kushala Alpha",
        get_id(130): "Kushala Beta",
        get_id(131): "Death Stench Alpha",
        get_id(132): "Death Stench Beta",
        get_id(135): "Guild Cross Alpha",
        get_id(136): "Guild Cross Beta",
        get_id(151): "Commission Alpha",
        get_id(152): "Commission Beta",
        get_id(191): "Kulve Taroth Alpha",
        get_id(192): "Kulve Taroth Beta",
        get_id(206): "Drachen Armet Alpha",
        get_id(207): "Drachen Armet Alpha",
        get_id(218): "Vaal Hazak Gamma",
        get_id(219): "Kirin Gamma",
        get_id(220): "Kaiser Gamma",
        get_id(221): "Kushala Gamma",
        get_id(222): "Nergigante Gamma",
        get_id(223): "Zorah Gamma",
        get_id(224): "Xeno'jiva Gamma",
        get_id(231): "Empress Alpha",
        get_id(232): "Empress Beta",
        get_id(253): "Empress Gamma",
        get_id(258): "Kulve Taroth Gamma",
    }
}

ARMOR_SUFFIXES = ["Helm", "Mail", "Vambrace", "Coil", "Greaves"]
armors_by_rarity = {}
for rarity, items in armor_sets_by_rarity.items():
    new_items = {}
    for base_id, name in items.items():
        for offset, suffix in enumerate(ARMOR_SUFFIXES):
            new_items[base_id + offset] = f"{name} {suffix}"
    armors_by_rarity[rarity] = new_items
